### ISSUE TITLE
Why do I feel pulled to using 'p' and 'n' for paging up and down?

### ISSUE THREAD

**Issue by greganderson** [greganderson/BrowserVim#7]
Any ideas?  It feels so natural to do that, but I don't know why.  When using Vim I feel perfectly fine using ctrl+u and ctrl+d for paging up and down, so why 'p' and 'n'?  Should we change it to that instead?  It makes it easier to just use one hand.  What do you think?

**Comment by greganderson** [comment]
Or as another idea, you could use either 'u' and 'd' or 'p' and 'n'.  That's an option too.

**Comment by unaveed** [comment]
I feel that 'u' and 'd' feels more natural and is more intuitive.

**Comment by greganderson** [comment]
Okay we'll keep that then.
